### ISSUE TITLE
Windows builds fail, sometimes

### ISSUE THREAD

**Issue by jackjansen** [MotionSpell/lldash#29]
Pulled out of #17, which was a big mash-mash of unrelated issues, it turned out.

> Next problem with the Windows build: `ffmpeg` doesn't build.
> 
> Inspected the uploaded vcpkg build tree, and  `ffmpeg/build-x64-mingw-dynamic-rel-out.log` shows that the configure worked fine (it seems) but then `make` didn't do anything.
> 
> Inspecting `build-x64-mingw-dynamic-rel-err.log` shows 
> 
> ```
> Makefile:1: /d/a/lldash/lldash/vcpkg/buildtrees/ffmpeg/src/n7.1.1-07cb3aa68a.clean/Makefile: No such file or directory
> make: *** No rule to make target '/d/a/lldash/lldash/vcpkg/buildtrees/ffmpeg/src/n7.1.1-07cb3aa68a.clean/Makefile'.  Stop.
> ```
> 
> This is very strange, because I clearly see that the file exists... 

 _Originally posted by @jackjansen in [#17](https://github.com/MotionSpell/lldash/issues/17#issuecomment-2809738323)_

**Comment by jackjansen** [comment]
> One of the things I’m wondering is whether the version of msys2 has any bearing on the situation. Probably specifically the developer tools (including pkgconfig).

**Comment by jackjansen** [comment]
Another possible data point: tried a Github Action build yesterday (on an unrelated branch), and it failed in the `vcpkg` build of ffmpeg`.  

Log is here for the time being: https://github.com/MotionSpell/lldash/actions/runs/14716486412/job/41300961037#step:14:3

However, the failure was completely different from earlier ones that I remember: it managed to configure ffmpeg but then it couldn't find `make`. Around line 3480:

```
Error:   vcpkg install failed.  See logs for more information:
    D:/a/lldash/lldash/build/vcpkg-manifest-install.log
  Call Stack (most recent call first):
    D:/a/_temp/-622080889/cmake-3.31.7-windows-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:146 (include)
    CMakeLists.txt:24 (project)
  
  
  CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
  CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
```

**Comment by jackjansen** [comment]
So, from https://github.com/MotionSpell/lldash/issues/29#issuecomment-2838690507 I learn that we must also specify that you install 64 bit mingw.

And earlier in the conversation I learned that we must warn people against the cmake GUI.

**Comment by shivivats** [comment]
So the build is now working(!) in **both** `cmake GUI` and `vscode` now. It seems like if the configurations/paths are correct then both will work.

Fixing the `PKG_CONFIG_EXECUTABLE` was quite straightforward actually... I simply installed `pkgconf` using `.\vcpkg.exe install pkgconf` and set the `PKG_CONFIG_EXECUTABLE` variable to `C:\vcpkg\packages\pkgconf_x64-windows\tools\pkgconf\pkgconf.exe` (aka the location of the executable in my `vcpkg` installation).

I do note here that this is another vcpkg build that I have on my PC and not the vcpkg that comes with the project. Trying now with the vcpkg that comes with the repo...

As to this:

> Another possible data point: tried a Github Action build yesterday (on an unrelated branch), and it failed in the `vcpkg` build of ffmpeg`.
> 
> Log is here for the time being: https://github.com/MotionSpell/lldash/actions/runs/14716486412/job/41300961037#step:14:3
> 
> However, the failure was completely different from earlier ones that I remember: it managed to configure ffmpeg but then it couldn't find `make`. Around line 3480:
> 
> ```
> Error:   vcpkg install failed.  See logs for more information:
>     D:/a/lldash/lldash/build/vcpkg-manifest-install.log
>   Call Stack (most recent call first):
>     D:/a/_temp/-622080889/cmake-3.31.7-windows-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:146 (include)
>     CMakeLists.txt:24 (project)
>   
>   
>   CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
>   CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> ```


I had this exact error earlier. I fixed it by setting a `CMAKE_MAKE_PROGRAM` variable to the location of the `mingw32-make.exe` on my PC (after ensuring I had 64-bit `mingw` installed) in the `cmake` config. The `bin` folder of the `mingw32-make.exe` was already in my `PATH` but `cmake` was still unable to find it.

**Comment by jackjansen** [comment]
> I had this exact error earlier. I fixed it by setting a CMAKE_MAKE_PROGRAM variable to the location of the mingw32-make.exe on my PC (after ensuring I had 64-bit mingw installed) in the cmake config. The bin folder of the mingw32-make.exe was already in my PATH but cmake was still unable to find it.

This is strange... (That it can't find `mingw32-make`). Where and how did you "set a CMAKE_MAKE_PROGRAM"? In the lldash toplevel `CMakeLists`?

**Comment by shivivats** [comment]
I added it to the `CMakePresets.json` file in both the windows presets, like so:

```
		{
			"name": "mingw-production",
			"description": "Build for production on Windows with mingw",
			"inherits": "mingw",
			"cacheVariables": {
				"CMAKE_BUILD_TYPE": "Release",
				"CMAKE_MAKE_PROGRAM": "C:/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/bin/mingw32-make.exe",
			}

		},
```
```
		{
			"name": "mingw-develop",
			"description": "Build for development on Windows with mingw",
			"inherits": "mingw",
			"cacheVariables": {
				"CMAKE_BUILD_TYPE": "RelWithDebInfo",
				"CMAKE_MAKE_PROGRAM": "C:/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/bin/mingw32-make.exe",
			}
		},
```

**Comment by shivivats** [comment]
So unfortunately, I pulled the latest version (I think I had pulled up to [this](https://github.com/MotionSpell/lldash/commit/bdd8a085902110ff6699377b52e4090ce89125a7) commit before ) and now the build is not working again with the following error:

```
[cmake]   include could not find requested file:
[cmake] 
[cmake]     GetGitVersion
[cmake] 
[cmake] 
[cmake] CMake Error at CMakeLists.txt:13 (get_git_version):
[cmake]   Unknown CMake command "get_git_version".
```

I see that you've encountered this error before. Do you have any tips to fix it?
Of course I can just roll back and see if it works, but I thought its worth to ask to fix it going forward

**Comment by jackjansen** [comment]
Something has thrown away your `CMakeFiles` directory. `git checkout -- CMakeFiles` should fix it. I've had this happen to me in different projects years ago, but I haven't seen it happen recently.

**Comment by jackjansen** [comment]
On the `make` issue:

> 	`"CMAKE_MAKE_PROGRAM": "C:/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/bin/mingw32-make.exe",`

That path looks very strange to me, especially the first bit (the `/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/`). 

I have followed https://code.visualstudio.com/docs/cpp/config-mingw which pointed me towards MSYS2, which seemed to work, so I've basically followed that for all other machines (including the Github Actions runners).

I _have_ found out in the mean time that there are `PATH` issues with the various MSYS versions, maybe these are what causes `mingw32-cmake` not to be found...

How did you install msys2?

**Comment by jackjansen** [comment]
@shivivats I have created a branch `29-windows-build` where I'm creating the instructions and scripts to do a build. I'll let you know when it works for me:-)

**Comment by shivivats** [comment]
> On the `make` issue:
> 
> > `"CMAKE_MAKE_PROGRAM": "C:/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/mingw64/bin/mingw32-make.exe",`
> 
> That path looks very strange to me, especially the first bit (the `/mingw-w64/x86_64-8.1.0-release-posix-seh-rt_v6-rev0/`).
> 
> I have followed https://code.visualstudio.com/docs/cpp/config-mingw which pointed me towards MSYS2, which seemed to work, so I've basically followed that for all other machines (including the Github Actions runners).
> 
> I _have_ found out in the mean time that there are `PATH` issues with the various MSYS versions, maybe these are what causes `mingw32-cmake` not to be found...
> 
> How did you install msys2?

I installed it using the link there as well. However, I encountered a ton of issues with paths (even after double checking there wasnt any spaces in the path, and that the path was added to both system and user PATH variables). Issues persisted after a restart as well. I then found out that I had a mingw installation already in the "Program Files" folder which wouldnt work due to the space in the folder name, so I moved it up to "C:\", put it into the PATH variable and CMAKE, and everything worked.

However, I might have missed the part where I install gcc after installing Msys2.... will look into it and get back to you.

**Comment by jackjansen** [comment]
Ha! running the cmake configure a second time it suddenly works!

**Comment by jackjansen** [comment]
Lo and behold... Using `msys` on the Github actions runner (in stead of powershell) to do the building also works!

**Comment by jackjansen** [comment]
Next issue:  https://github.com/cwi-dis/cwipc/issues/196 needs to be fixed.

**Comment by shivivats** [comment]
Soo it seems like you had some success over the weekend/before the weekend @jackjansen 

But I am, unfortunately, stuck again. Cmake configures and generates without any issue, but currently the following warning (being treated as an error) is occuring. I tried to temporarily bypass it by commenting the code line out, but I see many more warnings (being treated as errors) afterwards.

Any pointers?

My first thought is it might be a `gcc`/`g++` version mismatch (i.e. the version being used to develop is different than the version I have and my version has different rules for warnings). For reference, I have `g++` and `gcc` ver. `14.2.0`.

```
[build] [  0%] Building CXX object lldash-relay/CMakeFiles/evanescent.dir/src/tcp_server_windows.cpp.obj
[build] C:\Users\nb-lenovo-40\Desktop\lldash\lldash-relay\src\tcp_server_windows.cpp: In function 'void runTcpServer(int, std::function<void(std::unique_ptr<IStream>)>)':
[build] C:\Users\nb-lenovo-40\Desktop\lldash\lldash-relay\src\tcp_server_windows.cpp:135:19: error: comparison of integer expressions of different signedness: 'SOCKET' {aka 'long long unsigned int'} and 'int' [-Werror=sign-compare]
[build]   135 |       if(g_socket == -1)
[build]       |          ~~~~~~~~~^~~~~
[build] cc1plus.exe: all warnings being treated as errors
[build] mingw32-make[2]: *** [lldash-relay\CMakeFiles\evanescent.dir\build.make:109: lldash-relay/CMakeFiles/evanescent.dir/src/tcp_server_windows.cpp.obj] Error 1
[build] mingw32-make[1]: *** [CMakeFiles\Makefile2:806: lldash-relay/CMakeFiles/evanescent.dir/all] Error 2
[build] mingw32-make: *** [Makefile:155: all] Error 2
```


Also, in this particular example, I still dont understand how an `unsigned int` can be compared to `-1`. I did check that `g_socket` is of type `SOCKET` which is a `UINT_PTR` so perhaps this is just an overlooked bug?

**Comment by rbouqueau** [comment]
You need to update the code to ```if(g_socket == (SOCKET)-1)```. Setting an unsigned to -1 is a quite common trick to signal uninitialized values - in practice it puts all bits to one. I'm going to fix that for you.

**Comment by shivivats** [comment]
Ah, I see! I wasn't aware of the trick, but it makes sense! Thank you for the quick fix. Will get back to building on Windows and update this issue as to how it goes.

**Comment by shivivats** [comment]
**Build and install works!**

Pulled the latest version, vcpkg is updated, everything seems to be in order!!

I had to comment out the line `IOutput* output = otuputs[i].get();` in `helper.hpp` because I was getting the `unused variable` warning

```
C:\Users\...\lldash\signals\src\lib_modules\utils\helper.hpp:84:34: error: unused variable 'output' [-Werror=unused-variable]        
   84 |                         IOutput* output = outputs[i].get();
```

The next line was `return outputs[i].get();` so I guess I could've just returned the var instead of commenting the line, but doesnt make a difference either way (I hope).
To be noted that I had the same warning/error before as well and commented out the same line to get the build to succeed before.

Also to be noted that I still have the `"CMAKE_MAKE_PROGRAM": "C:\\msys64\\ucrt64\\bin\\mingw32-make.exe"` added to my `CMakePresets.txt` to the `cacheVariables` for the `mingw-production` and `mingw-develop` presets (using the latter here).

Thanks Jack and Romain for your help!
